version: '3.8'

services:

  dockerhost:
    image: qoomon/docker-host
    restart: "no"
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  dummy:
    image: bash
    command: ["ping" , "dockerhost"]

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    restart: "no"
    hostname: zookeeper-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "12181:12181"
    mem_limit: 600m
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-1"
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    restart: "no"
    hostname: zookeeper-2
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "22181:22181"
    mem_limit: 600m
    volumes:
      - ../jolokia:/opt/jolokia
    depends_on:
      - zookeeper-1
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-2"
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    restart: "no"
    hostname: zookeeper-3
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "32181:32181"
    mem_limit: 600m
    depends_on:
      - zookeeper-2
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-3"
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    restart: "no"
    hostname: kafka-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "19092:19092"
    mem_limit: 1500m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    restart: "no"
    hostname: kafka-2
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "29092:29092"
    mem_limit: 1500m
    depends_on:
      - kafka-1
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-2"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    restart: "no"
    hostname: kafka-3
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "39092:39092"
    mem_limit: 1500m
    depends_on:
      - kafka-1
      - kafka-2
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-3"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-connect-1:
    image: confluentinc/cp-kafka-connect:latest
    restart: "no"
    hostname: kafka-connect-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:connect"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "18082:18082"
    mem_limit: 1500m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
      - ../splunk-kafka-connect:/etc/kafka-connect/jars/splunk-kafka-connect
      - ../kafka-connect-datagen/confluentinc-kafka-connect-datagen:/etc/kafka-connect/jars/confluentinc-kafka-connect-datagen
      - ../kafka-connect-syslog/confluentinc-kafka-connect-syslog:/etc/kafka-connect/jars/confluentinc-kafka-connect-syslog
      - ../kafka-connect:/etc/kafka-connect/config
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-connect-1"
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
    command: "/usr/bin/connect-distributed /etc/kafka-connect/config/connect-distributed.properties-kafka-connect-1"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    restart: "no"
    hostname: schema-registry
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:schema-registry"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18081:18081"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "schema-registry"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:29092,PLAINTEXT://kafka-3:39092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:18081"
      SCHEMA_REGISTRY_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  ksql-server:
    image: confluentinc/cp-ksql-server:latest
    restart: "no"
    hostname: ksql-server
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:ksql-server"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18088:18088"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "ksql-server"
      KSQL_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:29092,PLAINTEXT://kafka-3:39092"
      KSQL_KSQL_SERVICE_ID: "confluent_standalone_1_"
      KSQL_LISTENERS: "http://0.0.0.0:18088"
      KSQL_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    restart: "no"
    hostname: kafka-rest
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:kafka-rest"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18089:18089"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-rest"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:29092,PLAINTEXT://kafka-3:39092"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181"
      KAFKA_REST_LISTENERS: "http://localhost:18089"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:18083"
      KAFKAREST_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      KAFKA_REST_HOST_NAME: "kafka-rest"

  telegraf:
    image: telegraf:latest
    restart: "no"
    environment:
      env: "docker_env"
      label: "testing"
      host: "telegraf"
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      SPLUNK_HEC_URL: "https://host.docker.internal:8088"
      SPLUNK_HEC_TOKEN: "205d43f1-2a31-4e60-a8b3-327eda49944a"
    hostname: telegraf
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:telegraf"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  burrow:
    image: guilhemmarchand/burrow:latest
    restart: "no"
    hostname: burrow
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:burrow"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - 9002:9002
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../burrow/config:/etc/burrow/
      - ../burrow/tmp:/var/tmp/burrow
    environment:
      env: "docker_env"
      label: "testing"
      host: "burrow"

  kafka-monitor:
    image: guilhemmarchand/kafka-monitor:latest
    restart: "no"
    hostname: kafka-monitor
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka-monitor"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../kafka-monitor:/usr/local/share/kafka-monitor
    command: "/opt/kafka-monitor/bin/kafka-monitor-start.sh /usr/local/share/kafka-monitor/kafka-monitor.properties"
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-monitor"

  confluent-interceptor:
    image: confluentinc/cp-enterprise-control-center
    restart: "no"
    hostname: confluent-interceptor
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://host.docker.internal:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-index: "confluent_interceptor_metrics"
        splunk-sourcetype: "confluent_interceptor"
        splunk-format: "raw"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 600m
    volumes:
      - ../confluent/control-center.properties:/etc/confluent-control-center/control-center.properties
    environment:
      env: "docker_env"
      label: "testing"
      host: "confluent-consumer-interceptor"
    command: "/usr/bin/control-center-console-consumer /etc/confluent-control-center/control-center.properties --topic _confluent-monitoring"

  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    restart: "no"
    hostname: kafka-manager
    ports:
      - "9000:9000"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      ZK_HOSTS: "zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: "admin"
      KAFKA_MANAGER_PASSWORD: "ch@ngeM3"
