version: '2.4'
services:

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  dummy:
    image: bash
    command: ["ping" , "dockerhost"]

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "12181:12181"
    mem_limit: 600m
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-1"
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-2
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "22181:22181"
    mem_limit: 600m
    volumes:
      - ../jolokia:/opt/jolokia
    depends_on:
      - zookeeper-1
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-2"
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-3
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:zookeeper"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "32181:32181"
    mem_limit: 600m
    depends_on:
      - zookeeper-2
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "zookeeper-3"
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "19092:19092"
    mem_limit: 1500m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "29092:29092"
    mem_limit: 1500m
    depends_on:
      - kafka-1
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-2"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:broker"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "39092:39092"
    mem_limit: 1500m
    depends_on:
      - kafka-1
      - kafka-2
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-3"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      JMX_PORT: "9999"

  kafka-connect-1:
    image: confluentinc/cp-kafka-connect:latest
    hostname: kafka-connect-1
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka:connect"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    ports:
      - "18082:18082"
    mem_limit: 1500m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
      - ../splunk-kafka-connect:/etc/kafka-connect/jars/splunk-kafka-connect
      - ../kafka-connect-datagen/confluentinc-kafka-connect-datagen:/etc/kafka-connect/jars/confluentinc-kafka-connect-datagen
      - ../kafka-connect-syslog/confluentinc-kafka-connect-syslog:/etc/kafka-connect/jars/confluentinc-kafka-connect-syslog
      - ../kafka-connect:/etc/kafka-connect/config
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-connect-1"
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
    command: "/usr/bin/connect-distributed /etc/kafka-connect/config/connect-distributed.properties-kafka-connect-1"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:schema-registry"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18081:18081"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "schema-registry"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:29092,PLAINTEXT://kafka-3:39092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:18081"
      SCHEMA_REGISTRY_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  ksql-server:
    image: confluentinc/cp-ksql-server:latest
    hostname: ksql-server
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:ksql-server"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18088:18088"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "ksql-server"
      KSQL_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:29092,PLAINTEXT://kafka-3:39092"
      KSQL_KSQL_SERVICE_ID: "confluent_standalone_1_"
      KSQL_LISTENERS: "http://0.0.0.0:18088"
      KSQL_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"

  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    hostname: kafka-rest
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:confluent:kafka-rest"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - "18089:18089"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../jolokia:/opt/jolokia
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-rest"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181"
      KAFKA_REST_LISTENERS: "http://localhost:18089"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:18083"
      KAFKAREST_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
      KAFKA_REST_HOST_NAME: "kafka-rest"

  telegraf:
    image: telegraf:latest
    restart: always
    environment:
      env: "docker_env"
      label: "testing"
      host: "telegraf"
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      SPLUNK_HEC_URL: "https://dockerhost:8088"
      SPLUNK_HEC_TOKEN: "205d43f1-2a31-4e60-a8b3-327eda49944a"
    hostname: telegraf
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:telegraf"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  burrow:
    image: guilhemmarchand/burrow:latest
    restart: always
    hostname: burrow
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:burrow"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    ports:
      - 9002:9002
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../burrow/config:/etc/burrow/
      - ../burrow/tmp:/var/tmp/burrow
    environment:
      env: "docker_env"
      label: "testing"
      host: "burrow"

  kafka-monitor:
    image: guilhemmarchand/kafka-monitor:latest
    hostname: kafka-monitor
    logging:
      driver: splunk
      options:
        splunk-token: "11113ee7-919e-4dc3-bde6-da10a2ac6709"
        splunk-url: "https://dockerhost:8088"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-sourcetype: "docker:kafka-monitor"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        env: "env,label,host"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ../kafka-monitor:/usr/local/share/kafka-monitor
    command: "/opt/kafka-monitor/bin/kafka-monitor-start.sh /usr/local/share/kafka-monitor/kafka-monitor.properties"
    environment:
      env: "docker_env"
      label: "testing"
      host: "kafka-monitor"

  # This "container" is a workaround to pre-create topics for the Kafka Music application
  # until we have a more elegant way to do that.
  kafka-create-topics:
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    hostname: kafka-create-topics
    # We defined a dependency on "kafka", but `depends_on` will NOT wait for the
    # dependencies to be "ready" before starting the "kafka-create-topics"
    # container;  it waits only until the dependencies have started.  Hence we
    # must control startup order more explicitly.
    # See https://docs.docker.com/compose/startup-order/
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                        cub kafka-ready -b kafka-1:19092 1 20 && \
                        kafka-topics --create --topic play-events --if-not-exists --zookeeper zookeeper-1:12181 --partitions 4 --replication-factor 1 && \
                        kafka-topics --create --topic song-feed --if-not-exists --zookeeper zookeeper-1:12181 --partitions 4 --replication-factor 1 && \
                        sleep infinity'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    mem_limit: 300m

  # Continuously generates input data for the Kafka Music application.
  kafka-music-data-generator:
    image: confluentinc/kafka-streams-examples:5.0.0
    hostname: kafka-music-data-generator
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
      - kafka-create-topics
    # Control startup order similarly to the "kafka-create-topics" container above.
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                        cub kafka-ready -b kafka-1:19092 1 20 && \
                        echo Waiting for Confluent Schema Registry to be ready... && \
                        cub sr-ready schema-registry 18081 20 && \
                        java -cp /usr/share/java/kafka-streams-examples/kafka-streams-examples-5.0.0-standalone.jar \
                        io.confluent.examples.streams.interactivequeries.kafkamusic.KafkaMusicExampleDriver \
                        kafka-1:19092 http://schema-registry:18081'"
    environment:
      STREAMS_BOOTSTRAP_SERVERS: ignored
      STREAMS_SCHEMA_REGISTRY_HOST: ignored
      STREAMS_SCHEMA_REGISTRY_PORT: ignored
      KAFKA_MUSIC_APP_REST_HOST: ignored
      KAFKA_MUSIC_APP_REST_PORT: ignored
    mem_limit: 300m

  # Runs the Kafka Music application.
  kafka-music-application:
    image: confluentinc/kafka-streams-examples:5.0.0
    hostname: kafka-music-application
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
      - kafka-create-topics
    volumes:
      - ../jolokia:/opt/jolokia
      - ../kafka-streams:/opt/kafka-streams
    # Control startup order similarly to the "kafka-create-topics" container above.
    # Note: The container's `run` script will perform the same readiness checks
    # for Kafka and Confluent Schema Registry, but that's ok because they complete fast.
    # The reason we check for readiness here is that we can insert a sleep time
    # for topic creation before we start the application.
    #
    # TODO: Once https://issues.apache.org/jira/browse/KAFKA-5037 is resolved,
    #       we can remove this `command` and use the image as-is.
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                        cub kafka-ready -b kafka-1:19092 1 20 && \
                        echo Waiting for Confluent Schema Registry to be ready... && \
                        cub sr-ready schema-registry 18081 20 && \
                        echo Waiting a few seconds for topic creation to finish... && \
                        sleep 2 && \
                        /etc/confluent/docker/run'"
    ports:
      - '7070:7070'
    mem_limit: 300m
    environment:
      STREAMS_BOOTSTRAP_SERVERS: kafka-1:19092
      STREAMS_SCHEMA_REGISTRY_HOST: schema-registry
      STREAMS_SCHEMA_REGISTRY_PORT: 18081
      KAFKA_MUSIC_APP_REST_HOST: localhost
      KAFKA_MUSIC_APP_REST_PORT: 7070

  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    hostname: kafka-manager
    ports:
      - "9000:9000"
    mem_limit: 300m
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      ZK_HOSTS: "zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: "admin"
      KAFKA_MANAGER_PASSWORD: "ch@ngeM3"
